name: phishield

services:
  frontend:
    build: ./frontend
    image: frontend
    container_name: frontend
    ports:
      - "8000:8000"

  backend:
    build: ./backend
    image: backend
    container_name: backend
    ports: 
      - "8001:8001"
    env_file:
      - .env
    environment:
      - DB_PATH=/app/phishing.db        # container sees this path
    volumes:
      - ${DB_PATH}:/app/phishing.db     # host path from .env, mounts to /app/phishing.db
